import { Contact } from './definitions';

const contacts: Contact[] = [
  {
    id: '1',
    name: 'Ana Beatriz Souza',
    email: 'ana.souza@example.com',
    phone: '(11) 91234-5678',
    birth_date: '1990-03-14',
    gender: 'feminino',
    situation: 'cliente',
  },
  {
    id: '2',
    name: 'Carlos Eduardo Lima',
    email: 'carlos.lima@example.com',
    phone: '(21) 99876-5432',
    birth_date: '1985-07-22',
    gender: 'masculino',
    situation: 'cliente',
  },
  {
    id: '3',
    name: 'Beatriz Fernandes',
    email: 'beatriz.fernandes@example.com',
    phone: '(31) 98765-4321',
    birth_date: '1993-11-02',
    gender: 'feminino',
    situation: 'lead',
  },
  {
    id: '4',
    name: 'Diego Martins',
    email: 'diego.martins@example.com',
    phone: '(41) 99654-3210',
    birth_date: '1988-01-30',
    gender: 'masculino',
    situation: 'ex-cliente',
  },
  {
    id: '5',
    name: 'Fernanda Costa',
    email: 'fernanda.costa@example.com',
    phone: '(51) 98543-2109',
    birth_date: '1995-05-18',
    gender: 'feminino',
    situation: 'cliente',
  },
  {
    id: '6',
    name: 'Gustavo Ribeiro',
    email: 'gustavo.ribeiro@example.com',
    phone: '(61) 97432-1098',
    birth_date: '1979-09-09',
    gender: 'masculino',
    situation: 'lead',
  },
  {
    id: '7',
    name: 'Helena Cardoso',
    email: 'helena.cardoso@example.com',
    phone: '(71) 96321-0987',
    birth_date: '2000-12-25',
    gender: 'feminino',
    situation: 'cliente',
  },
  {
    id: '8',
    name: 'Igor Almeida',
    email: 'igor.almeida@example.com',
    phone: '(81) 95210-9876',
    birth_date: '1991-06-11',
    gender: 'masculino',
    situation: 'cliente',
  },
  {
    id: '9',
    name: 'Juliana Pereira',
    email: 'juliana.pereira@example.com',
    phone: '(91) 94109-8765',
    birth_date: '1987-02-27',
    gender: 'feminino',
    situation: 'ex-cliente',
  },
  {
    id: '10',
    name: 'Lucas Barbosa',
    email: 'lucas.barbosa@example.com',
    phone: '(92) 93098-7654',
    birth_date: '1996-08-19',
    gender: 'masculino',
    situation: 'lead',
  },
];

export default contacts;
